"""Generate the demo pack: twenty sound effects and twenty music beds.

Everything here is generated by ElevenLabs, not recorded and not sampled from
anyone's library. That is the point, the pack ships with the app, so it has to
be ours to give away.

    python tools/make_demo_pack.py --check     # what it would cost, spends nothing
    python tools/make_demo_pack.py             # generate anything still missing
    python tools/make_demo_pack.py --only bed  # just the beds
    python tools/make_demo_pack.py --force     # regenerate even if the file exists

Generating costs credits, so --check first and say the number out loud before
running it for real. Files that already exist are skipped, which makes this
safe to re-run after a network wobble.
"""

from __future__ import annotations

import argparse
import io
import json
import os
import sys
import time
import urllib.error
import urllib.request

import soundfile as sf

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from audiopost import LOOP_CROSSFADE_SECONDS, write_bed, write_sfx
from dropdeck import constants as C

API = "https://api.elevenlabs.io"
SFX_ENDPOINT = "/v1/sound-generation"
MUSIC_ENDPOINT = "/v1/music"

#: What ElevenLabs charges, so --check can tell the truth without calling out.
CREDITS_PER_SFX_SECOND = 40
CREDITS_PER_MUSIC_MINUTE = 900

BED_SECONDS = 30
#: Ask for a little more than we keep. MP3 padding and the loop crossfade both
#: come off the end, and we would rather trim than come up short.
BED_REQUEST_SECONDS = BED_SECONDS + 2.0

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEMO_DIR = os.path.join(HERE, "demo")

# --------------------------------------------------------------- the pack ---
# (bank slot 1-20, file stem, spoken name, prompt, seconds)
SFX = [
    (1, "applause", "applause",
     "Warm enthusiastic audience applause in a studio, building quickly and "
     "settling naturally. Clean, no music, no voices.", 4.0),
    (2, "cheer", "crowd cheer",
     "A delighted crowd cheering and whooping, close and lively. "
     "No music, no speech.", 3.0),
    (3, "laughter", "audience laugh",
     "A studio audience laughing warmly together, then trailing off. "
     "No music, no words.", 3.0),
    (4, "buzzer", "buzzer",
     "A harsh electric game show buzzer for a wrong answer, short and blunt.", 1.5),
    (5, "ding", "correct ding",
     "A single bright bell ding for a correct answer, clean with a short tail.", 1.5),
    (6, "airhorn", "air horn",
     "A loud reggae DJ air horn blast, punchy and brash.", 2.0),
    (7, "whoosh", "whoosh",
     "A fast smooth whoosh transition passing left to right, airy, no music.", 1.5),
    (8, "riser", "riser",
     "A tension riser building steadily to a peak then cutting off, "
     "cinematic, no drums.", 4.0),
    (9, "impact", "impact boom",
     "A deep cinematic braaam impact with a long low tail, trailer style.", 3.0),
    (10, "rimshot", "rimshot",
     "A comedy drum rimshot sting, ba dum tss, dry snare and crash cymbal.", 2.0),
    (11, "scratch", "record scratch",
     "A vinyl record scratching to an abrupt stop, turntable needle skid.", 1.5),
    (12, "kaching", "cash register",
     "A cash register ka-ching with coins tumbling, bright and cheerful.", 2.0),
    (13, "shutter", "camera shutter",
     "A single crisp camera shutter click, mechanical SLR.", 1.0),
    (14, "phone", "phone ring",
     "An old fashioned telephone ringing twice, mechanical bell.", 3.0),
    (15, "notify", "notification",
     "A soft friendly notification pop, two quick tones, modern app.", 1.0),
    (16, "swoosh_up", "rising swoosh",
     "A rising swoosh transition sweeping upward, clean and airy.", 1.5),
    (17, "thunder", "thunder",
     "A distant thunder rumble rolling across the sky, deep and wide.", 5.0),
    (18, "knock", "door knock",
     "Three firm knocks on a solid wooden door, close and dry.", 2.0),
    (19, "crickets", "crickets",
     "Awkward silence crickets chirping at night, sparse and dry, comedic.", 4.0),
    (20, "drumroll", "drum roll",
     "A snare drum roll building and ending with a cymbal crash.", 4.0),
]

# (bank slot 1-20, file stem, spoken name, prompt)
BEDS = [
    (1, "lofi_chill", "lo-fi chill",
     "A relaxed lo-fi hip hop instrumental bed. Dusty piano chords, soft "
     "boom bap drums, warm vinyl crackle, mellow bass. Steady, loopable, "
     "no vocals, nothing attention grabbing."),
    (2, "upbeat_pop", "upbeat pop",
     "A bright cheerful pop instrumental bed. Plucky synths, clapping "
     "backbeat, bouncy bass, optimistic. Steady, loopable, no vocals."),
    (3, "corporate_uplift", "corporate uplift",
     "A clean uplifting corporate instrumental bed. Gentle piano, soft "
     "strings, light percussion, hopeful and unobtrusive. No vocals."),
    (4, "dark_tension", "dark tension",
     "A dark tense instrumental bed. Low drones, sparse pulses, unsettling "
     "strings, restrained. Loopable, no vocals, no big hits."),
    (5, "funky_groove", "funky groove",
     "A funky instrumental groove bed. Wah guitar, tight drums, slap bass, "
     "brass stabs, seventies flavour. Loopable, no vocals."),
    (6, "ambient_pad", "ambient pad",
     "A calm ambient instrumental bed. Slow evolving warm pads, faint "
     "shimmer, no drums, no melody. Very soft, loopable, no vocals."),
    (7, "news_urgent", "news urgency",
     "An urgent news broadcast instrumental bed. Driving pulse, ticking "
     "rhythm, tense strings, authoritative. Loopable, no vocals."),
    (8, "cinematic_epic", "cinematic epic",
     "An epic cinematic instrumental bed. Swelling strings, deep drums, "
     "brass, heroic and wide. Loopable, no vocals."),
    (9, "synthwave", "synthwave",
     "A retro synthwave instrumental bed. Analog arpeggios, gated drums, "
     "neon pads, eighties. Steady, loopable, no vocals."),
    (10, "acoustic_warm", "acoustic warm",
     "A warm acoustic instrumental bed. Fingerpicked guitar, light "
     "shaker, soft upright bass, homely and gentle. Loopable, no vocals."),
    (11, "boom_bap", "boom bap",
     "A classic boom bap hip hop instrumental bed. Punchy drums, dusty "
     "sample chords, deep bass, head nodding. Loopable, no vocals."),
    (12, "mystery", "mystery",
     "A curious mystery instrumental bed. Pizzicato strings, soft "
     "marimba, questioning melody, light and sneaky. Loopable, no vocals."),
    (13, "playful_quirky", "playful quirky",
     "A playful quirky instrumental bed. Ukulele, whistling, hand claps, "
     "light percussion, cheerful and silly. Loopable, no vocals."),
    (14, "sports_energy", "sports energy",
     "A high energy sports instrumental bed. Big drums, driving guitars, "
     "stadium claps, confident. Loopable, no vocals."),
    (15, "meditation", "meditation",
     "A serene meditation instrumental bed. Soft drones, gentle bells, "
     "slow breathing pace, no drums. Very calm, loopable, no vocals."),
    (16, "tech_electronic", "tech electronic",
     "A clean modern electronic instrumental bed. Crisp pulses, subtle "
     "arpeggio, tight kick, precise and futuristic. Loopable, no vocals."),
    (17, "suspense_pulse", "suspense pulse",
     "A suspenseful instrumental bed. A steady heartbeat pulse, sparse "
     "piano notes, rising unease, restrained. Loopable, no vocals."),
    (18, "documentary", "documentary",
     "A thoughtful documentary instrumental bed. Sparse piano, soft "
     "strings, reflective and unhurried. Loopable, no vocals."),
    (19, "celebration", "celebration",
     "A joyful celebration instrumental bed. Bright brass, festive "
     "percussion, triumphant and warm. Loopable, no vocals."),
    (20, "late_night_jazz", "late night jazz",
     "A smoky late night jazz instrumental bed. Brushed drums, walking "
     "upright bass, muted trumpet, relaxed piano. Loopable, no vocals."),
]


# ------------------------------------------------------------------- api ----
def load_key():
    """The key lives outside the repo and is never printed."""
    for path, field in (
            (os.path.expanduser("~/.eleven_tts/config.json"), "api_key"),
            (os.path.expanduser("~/Developer/video-use/.env"), "ELEVENLABS_API_KEY")):
        if not os.path.exists(path):
            continue
        if path.endswith(".json"):
            key = json.load(open(path, encoding="utf-8")).get(field)
        else:
            key = None
            for line in open(path, encoding="utf-8"):
                if line.startswith(field + "="):
                    key = line.split("=", 1)[1].strip().strip('"').strip("'")
        if key:
            return key
    raise SystemExit("No ElevenLabs API key found. Expected ~/.eleven_tts/config.json")


def post(path, payload, key, timeout=300):
    request = urllib.request.Request(
        API + path, data=json.dumps(payload).encode("utf-8"),
        headers={"xi-api-key": key, "Content-Type": "application/json"})
    with urllib.request.urlopen(request, timeout=timeout) as response:
        return response.read()


def credits_left(key):
    request = urllib.request.Request(API + "/v1/user/subscription",
                                     headers={"xi-api-key": key})
    with urllib.request.urlopen(request, timeout=30) as response:
        data = json.load(response)
    return data["character_limit"] - data["character_count"]


def call_with_retry(path, payload, key, label, attempts=3):
    for attempt in range(1, attempts + 1):
        try:
            return post(path, payload, key)
        except urllib.error.HTTPError as exc:
            body = exc.read().decode("utf-8", "replace")[:300]
            if exc.code in (429, 500, 502, 503, 504) and attempt < attempts:
                wait = 5 * attempt
                print(f"      {exc.code}, retrying in {wait}s")
                time.sleep(wait)
                continue
            raise SystemExit(f"\n{label} failed: HTTP {exc.code}\n{body}")
        except Exception as exc:
            if attempt < attempts:
                print(f"      {exc}, retrying")
                time.sleep(5 * attempt)
                continue
            raise SystemExit(f"\n{label} failed: {exc}")


# ------------------------------------------------------------------ jobs ----
def sfx_jobs():
    out = os.path.join(DEMO_DIR, "sfx")
    return [{
        "kind": "sfx", "slot": slot, "name": name, "prompt": prompt,
        "seconds": seconds, "path": os.path.join(out, f"{stem}.flac"),
        "credits": int(round(seconds * CREDITS_PER_SFX_SECOND)),
    } for slot, stem, name, prompt, seconds in SFX]


def bed_jobs():
    out = os.path.join(DEMO_DIR, "beds")
    per = int(round(BED_REQUEST_SECONDS / 60 * CREDITS_PER_MUSIC_MINUTE))
    return [{
        "kind": "bed", "slot": slot, "name": name, "prompt": prompt,
        "seconds": BED_SECONDS, "path": os.path.join(out, f"{stem}.ogg"),
        "credits": per,
    } for slot, stem, name, prompt in BEDS]


def generate(job, key):
    if job["kind"] == "sfx":
        raw = call_with_retry(SFX_ENDPOINT, {
            "text": job["prompt"],
            "duration_seconds": job["seconds"],
            "prompt_influence": 0.45,
            "model_id": "eleven_text_to_sound_v2",
            "output_format": "mp3_44100_128",
        }, key, job["name"])
        return write_sfx(raw, job["path"])

    raw = call_with_retry(MUSIC_ENDPOINT, {
        "prompt": job["prompt"],
        "music_length_ms": int(BED_REQUEST_SECONDS * 1000),
        "model_id": "music_v2",
        "force_instrumental": True,
    }, key, job["name"])
    return write_bed(raw, job["path"], job["seconds"])


# ----------------------------------------------------------------- board ----
def write_demo_board(durations):
    """A board whose paths are relative, so it works wherever the app lands."""
    slots = []
    for index in range(C.TOTAL_SLOTS):
        slots.append({"filepath": None, "name": None, "duration": None,
                      "custom_hotkey": None, "key_code": None,
                      "modifiers": None, "loop": False, "trim_db": 0.0})

    for slot, stem, name, _prompt, _seconds in SFX:
        rel = f"sfx/{stem}.flac"
        slots[slot - 1].update(filepath=rel, name=name,
                               duration=durations.get(rel), loop=False)
    for slot, stem, name, _prompt in BEDS:
        rel = f"beds/{stem}.ogg"
        index = (C.LOOPING_BANK - 1) * C.SLOTS_PER_BANK + slot - 1
        slots[index].update(filepath=rel, name=name,
                            duration=durations.get(rel), loop=True)

    board = {
        "app": C.APP_NAME,
        "format": 2,
        "sfx_volume": C.DEFAULT_SFX_VOLUME,
        "bed_volume": C.DEFAULT_BED_VOLUME,
        "ducking": True,
        "duck_db": C.DEFAULT_DUCK_DB,
        "device_name": None,
        "device_hostapi": None,
        "last_sound_dir": "",
        "slots": slots,
        "note": ("Demo pack. Every sound and bed was generated with ElevenLabs "
                 "AI, nothing here is recorded or sampled from a commercial "
                 "library."),
    }
    path = os.path.join(DEMO_DIR, "demo-board.json")
    with open(path, "w", encoding="utf-8") as handle:
        json.dump(board, handle, indent=2)
    return path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="show the plan and the cost, generate nothing")
    parser.add_argument("--only", choices=("sfx", "bed"), help="just one kind")
    parser.add_argument("--force", action="store_true",
                        help="regenerate even where the file already exists")
    parser.add_argument("--board-only", action="store_true",
                        help="rebuild demo-board.json from files already on disk")
    args = parser.parse_args()

    jobs = []
    if args.only != "bed":
        jobs += sfx_jobs()
    if args.only != "sfx":
        jobs += bed_jobs()

    for folder in ("sfx", "beds"):
        os.makedirs(os.path.join(DEMO_DIR, folder), exist_ok=True)

    if args.board_only:
        durations = {}
        for job in sfx_jobs() + bed_jobs():
            if os.path.exists(job["path"]):
                info = sf.info(job["path"])
                rel = os.path.relpath(job["path"], DEMO_DIR).replace("\\", "/")
                durations[rel] = info.frames / float(info.samplerate)
        print("wrote", write_demo_board(durations))
        return 0

    todo = [j for j in jobs if args.force or not os.path.exists(j["path"])]
    done = len(jobs) - len(todo)
    cost = sum(j["credits"] for j in todo)

    print(f"{C.APP_NAME} demo pack")
    print(f"  {len(jobs)} items, {done} already generated, {len(todo)} to make")
    print(f"  sound effects: {sum(1 for j in todo if j['kind'] == 'sfx')}")
    print(f"  music beds:    {sum(1 for j in todo if j['kind'] == 'bed')} "
          f"at {BED_SECONDS} seconds each")
    print(f"  estimated cost: {cost:,} credits")

    key = load_key()
    try:
        left = credits_left(key)
        print(f"  credits available: {left:,}")
        print(f"  left afterwards: {left - cost:,}")
        if cost > left:
            raise SystemExit("Not enough credits. Nothing was generated.")
    except urllib.error.URLError as exc:
        print(f"  (could not read the balance: {exc})")

    if args.check:
        print("\n--check only. Nothing was generated and nothing was spent.")
        return 0
    if not todo:
        print("\nEverything is already generated.")
        write_demo_board({})
        return 0

    print()
    durations = {}
    for number, job in enumerate(todo, start=1):
        rel = os.path.relpath(job["path"], DEMO_DIR).replace("\\", "/")
        print(f"  [{number:2}/{len(todo)}] {job['kind']} {job['slot']:2} "
              f"{job['name']:<18} ", end="", flush=True)
        seconds = generate(job, key)
        durations[rel] = seconds
        size = os.path.getsize(job["path"]) / 1024.0
        print(f"{seconds:5.1f}s  {size:7.0f} KB")

    # Pick up anything generated on an earlier run too.
    for job in jobs:
        rel = os.path.relpath(job["path"], DEMO_DIR).replace("\\", "/")
        if rel not in durations and os.path.exists(job["path"]):
            info = sf.info(job["path"])
            durations[rel] = info.frames / float(info.samplerate)

    print("\nwrote", write_demo_board(durations))
    total = sum(os.path.getsize(j["path"]) for j in jobs if os.path.exists(j["path"]))
    print(f"demo pack is {total / 1024 / 1024:.1f} MB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
